-- Insert sample franchise data
INSERT INTO franchises (
    id,
    name,
    description,
    category,
    investment_range_min,
    investment_range_max,
    franchise_fee,
    royalty_fee,
    territory,
    support_provided,
    requirements,
    contact_email,
    contact_phone,
    website_url,
    status,
    featured
) VALUES 
(
    uuid_generate_v4(),
    'Jollibee',
    'The Philippines'' favorite fast food chain serving burgers, fried chicken, and Filipino-style spaghetti.',
    'Food & Beverage',
    15000000.00,
    25000000.00,
    2000000.00,
    5.00,
    'Metro Manila',
    ARRAY['Site selection assistance', 'Training programs', 'Marketing support', 'Operations manual', 'Ongoing support'],
    ARRAY['Minimum 500 sqm floor area', 'High foot traffic location', 'Minimum 15M PHP liquid capital', 'Business experience preferred'],
    'franchise@jollibee.com.ph',
    '+63 2 8634 1111',
    'https://www.jollibee.com.ph',
    'active',
    true
),
(
    uuid_generate_v4(),
    'Goldilocks',
    'Leading bakeshop chain in the Philippines known for cakes, pastries, and Filipino delicacies.',
    'Food & Beverage',
    3000000.00,
    8000000.00,
    500000.00,
    4.00,
    'Nationwide',
    ARRAY['Store design assistance', 'Product training', 'Marketing campaigns', 'Supply chain support'],
    ARRAY['Minimum 80 sqm floor area', 'Commercial location', 'Minimum 3M PHP investment capacity'],
    'franchise@goldilocks.com.ph',
    '+63 2 8888 1000',
    'https://www.goldilocks.com.ph',
    'active',
    true
),
(
    uuid_generate_v4(),
    '7-Eleven Philippines',
    'Convenience store chain offering 24/7 service with food, beverages, and daily essentials.',
    'Retail',
    2500000.00,
    5000000.00,
    350000.00,
    3.50,
    'Urban areas',
    ARRAY['Store setup', 'Inventory management system', 'Staff training', '24/7 support hotline'],
    ARRAY['Minimum 60 sqm floor area', 'High visibility location', 'Parking availability preferred'],
    'franchise@7eleven.com.ph',
    '+63 2 8840 7711',
    'https://www.7eleven.com.ph',
    'active',
    false
),
(
    uuid_generate_v4(),
    'Potato Corner',
    'Popular snack franchise specializing in flavored french fries and other potato-based snacks.',
    'Food & Beverage',
    800000.00,
    1500000.00,
    200000.00,
    6.00,
    'Malls and commercial areas',
    ARRAY['Equipment package', 'Recipe and preparation training', 'Marketing materials', 'Site evaluation'],
    ARRAY['Minimum 15 sqm floor area', 'Mall or high-traffic location', 'Food service experience helpful'],
    'franchise@potatocorner.com',
    '+63 2 8631 8888',
    'https://www.potatocorner.com',
    'active',
    false
),
(
    uuid_generate_v4(),
    'Bench',
    'Fashion retail franchise offering trendy clothing and accessories for men and women.',
    'Fashion & Retail',
    5000000.00,
    12000000.00,
    1000000.00,
    5.00,
    'Shopping malls',
    ARRAY['Store design and layout', 'Merchandise planning', 'Staff training', 'Visual merchandising support'],
    ARRAY['Minimum 150 sqm floor area', 'Prime mall location', 'Fashion retail experience preferred'],
    'franchise@bench.com.ph',
    '+63 2 8856 0000',
    'https://www.bench.com.ph',
    'active',
    true
),
(
    uuid_generate_v4(),
    'Kumon Learning Center',
    'Educational franchise providing math and reading programs for children.',
    'Education',
    1200000.00,
    2500000.00,
    300000.00,
    0.00,
    'Residential and commercial areas',
    ARRAY['Instructor training', 'Curriculum materials', 'Student assessment tools', 'Marketing support'],
    ARRAY['Minimum 100 sqm floor area', 'Accessible location for families', 'Education background preferred'],
    'franchise@kumon.com.ph',
    '+63 2 8856 2222',
    'https://www.kumon.com.ph',
    'active',
    false
),
(
    uuid_generate_v4(),
    'Chowking',
    'Chinese fast food chain serving noodles, rice meals, and dim sum.',
    'Food & Beverage',
    8000000.00,
    15000000.00,
    1500000.00,
    5.00,
    'Metro Manila and key cities',
    ARRAY['Kitchen equipment', 'Recipe training', 'Operations manual', 'Marketing campaigns'],
    ARRAY['Minimum 200 sqm floor area', 'High foot traffic area', 'Restaurant experience preferred'],
    'franchise@chowking.com',
    '+63 2 8634 1111',
    'https://www.chowking.com',
    'active',
    false
),
(
    uuid_generate_v4(),
    'Ministop',
    'Convenience store with fresh food offerings and 24/7 operations.',
    'Retail',
    3000000.00,
    6000000.00,
    400000.00,
    3.00,
    'Urban and suburban areas',
    ARRAY['Store equipment', 'POS system', 'Product training', 'Ongoing operational support'],
    ARRAY['Minimum 80 sqm floor area', 'Corner lot preferred', 'Retail experience helpful'],
    'franchise@ministop.com.ph',
    '+63 2 8888 6464',
    'https://www.ministop.com.ph',
    'active',
    false
);

-- Note: In a real application, you would also insert corresponding user_profiles
-- for the franchise owners, but since we don't have actual user IDs from auth.users,
-- we'll leave the owner_id as NULL for now. These can be updated when real users
-- claim these franchises.
