// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ktugncuiwjoatopnialp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0dWduY3Vpd2pvYXRvcG5pYWxwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1MjUzNzYsImV4cCI6MjA2ODEwMTM3Nn0.Bciz3qMd0rzvS1gY5svqg46YQZ2vGoSzogKK2UE4kXg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});